[package]
name = "bssl-sys"
version = "0.1.0"
authors = ["Benjamin Brittain <bwb@google.com>", "David Drysdale <drysdale@google.com>"]
edition = "2018"

[dependencies]
libc = { version = "0.2", default-features = false }
